DROP DATABASE IF EXISTS TesteTableOrders;
CREATE DATABASE TesteTableOrders;

USE TesteTableOrders;
DROP TABLE IF EXISTS Tabela1;
DROP TABLE IF EXISTS Tabela11;
DROP TABLE IF EXISTS Tabela12;
DROP TABLE IF EXISTS Tabela111;
DROP TABLE IF EXISTS Tabela1111e121;

CREATE TABLE Tabela1
(
	id INT NOT NULL AUTO_INCREMENT,
	
	CONSTRAINT PK_Tabela1Id PRIMARY KEY CLUSTERED (id)
);

CREATE TABLE Tabela11
(
	id INT NOT NULL AUTO_INCREMENT,
	idTabela1_1 INT NOT NULL,
	
	CONSTRAINT PK_Tabela11Id PRIMARY KEY CLUSTERED (id, idTabela1_1),
	CONSTRAINT FK_Tabela1Id_1 FOREIGN KEY (idTabela1_1)
		REFERENCES Tabela1(id)
		ON UPDATE CASCADE
);

CREATE TABLE Tabela12
(
	id INT NOT NULL AUTO_INCREMENT,
	idTabela1_1 INT NOT NULL,
	
	CONSTRAINT PK_Tabela12Id PRIMARY KEY CLUSTERED (id, idTabela1_1),
	CONSTRAINT FK_Tabela1Id_2 FOREIGN KEY (idTabela1_1)
		REFERENCES Tabela1(id)
		ON UPDATE CASCADE
);

CREATE TABLE Tabela111
(
	id INT NOT NULL AUTO_INCREMENT,
	idTabela1_1 INT NOT NULL,
	idTabela11_11 INT NOT NULL,
	
	CONSTRAINT PK_Tabela12Id PRIMARY KEY CLUSTERED (id, idTabela1_1, idTabela11_11),
	CONSTRAINT FK_Tabela11Id FOREIGN KEY (idTabela1_1, idTabela11_11)
		REFERENCES Tabela11(id, idTabela1_1)
		ON UPDATE CASCADE
);

CREATE TABLE Tabela1111e121
(
	id INT NOT NULL AUTO_INCREMENT,
	idTabela1_111 INT NOT NULL,
	idTabela11_111 INT NOT NULL,
	idTabela111_111 INT NOT NULL,
	
	idTabela1_12 INT NOT NULL,
	idTabela12_12 INT NOT NULL,
	
	CONSTRAINT PK_Tabela1111e121Id PRIMARY KEY CLUSTERED (id, idTabela1_111, idTabela11_111, idTabela111_111, idTabela1_12, idTabela12_12),
	CONSTRAINT FK_Tabela111Id FOREIGN KEY (idTabela1_111, idTabela11_111, idTabela111_111)
		REFERENCES Tabela111(id, idTabela1_1, idTabela11_11)
		ON UPDATE CASCADE,
	CONSTRAINT FK_Tabela12Id FOREIGN KEY (idTabela1_12, idTabela12_12)
		REFERENCES Tabela12(id, idTabela1_1)
		ON UPDATE CASCADE
);