DROP TABLE IF EXISTS Tabela1;
DROP TABLE IF EXISTS Tabela2;

CREATE TABLE Tabela1
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	dadoTabela1 TEXT NOT NULL
);

CREATE TABLE Tabela2
(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	idTabela1 INTEGER NOT NULL,
	idTabela2 INTEGER NOT NULL,
	dadoTabela2 TEXT NOT NULL,

	CONSTRAINT FK_Tabela1 FOREIGN KEY (idTabela1)
		REFERENCES Tabela1(id)
		ON UPDATE CASCADE,

	CONSTRAINT FK_Tabela2 FOREIGN KEY (idTabela2)
		REFERENCES Tabela2(id)
		ON UPDATE CASCADE
);